# Generated by Django 5.1.4 on 2025-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.IntegerField(choices=[(0, 'Out of Stock'), (1, 'Low Stock'), (2, 'In Stock')], default=2),
        ),
    ]
